import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TradeAccountProvider } from "@/context/trade-account/trade-account-context";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "../_components/app-sidebar";
import DashboardHeader from "../_components/dashboard-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark `}
      >
        <TradeAccountProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="border-b px-4 py-2 flex items-center justify-between">
                <SidebarTrigger />
                <DashboardHeader />
              </header>
              <main className="w-full p-5">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </TradeAccountProvider>
        <Toaster position="top-left" />
      </body>
    </html>
  );
}
